import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";

const app = await readFile(new URL("../src/app.js", import.meta.url), "utf8");
const bookingRequestHtml = await readFile(new URL("../booking-request.html", import.meta.url), "utf8");
const bookingRequestCss = await readFile(new URL("../booking-request.css", import.meta.url), "utf8");
const bookingRequestJs = await readFile(new URL("../src/booking-request.js", import.meta.url), "utf8");
const indexHtml = await readFile(new URL("../index.html", import.meta.url), "utf8");
const styles = await readFile(new URL("../styles.css", import.meta.url), "utf8");
const supabase = await readFile(new URL("../src/supabase.js", import.meta.url), "utf8");
const server = await readFile(new URL("../server.mjs", import.meta.url), "utf8");
const automationApi = await readFile(new URL("../api/automation/send.js", import.meta.url), "utf8");
const memoryApi = await readFile(new URL("../api/memory/send.js", import.meta.url), "utf8");
const resendHelper = await readFile(new URL("../email/resend.mjs", import.meta.url), "utf8");
const vercelConfig = await readFile(new URL("../vercel.json", import.meta.url), "utf8");
const manifest = await readFile(new URL("../manifest.webmanifest", import.meta.url), "utf8");
const serviceWorker = await readFile(new URL("../sw.js", import.meta.url), "utf8");
const manifestData = JSON.parse(manifest);
const foundationMigration = await readFile(new URL("../supabase/migrations/001_phase1_foundation.sql", import.meta.url), "utf8");
const accessMigration = await readFile(new URL("../supabase/migrations/002_access_code_rls.sql", import.meta.url), "utf8");
const financialWorkflowMigration = await readFile(new URL("../supabase/migrations/004_phase1_financial_workflow.sql", import.meta.url), "utf8");
const checkinWorkflowMigration = await readFile(new URL("../supabase/migrations/005_phase1_checkin_workflow.sql", import.meta.url), "utf8");
const deleteMigration = await readFile(new URL("../supabase/migrations/006_calendar_history_pricing_delete.sql", import.meta.url), "utf8");
const checkoutCompletesMigration = await readFile(new URL("../supabase/migrations/007_checkout_settlement_completes_booking.sql", import.meta.url), "utf8");
const hardeningMigration = await readFile(new URL("../supabase/migrations/008_phase1_hardening.sql", import.meta.url), "utf8");
const bookingManagementMigration = await readFile(new URL("../supabase/migrations/009_phase2b_booking_management.sql", import.meta.url), "utf8");
const financeControlsMigration = await readFile(new URL("../supabase/migrations/010_phase2c_finance_controls.sql", import.meta.url), "utf8");
const drinksMigration = await readFile(new URL("../supabase/migrations/011_phase3a_drinks_inventory.sql", import.meta.url), "utf8");
const electricityMigration = await readFile(new URL("../supabase/migrations/012_phase3b_electricity_tracking.sql", import.meta.url), "utf8");
const simplifiedElectricityMigration = await readFile(new URL("../supabase/migrations/013_phase3b_simplify_electricity_tracker.sql", import.meta.url), "utf8");
const ownerHarvestMigration = await readFile(new URL("../supabase/migrations/014_phase3c_owner_harvest.sql", import.meta.url), "utf8");
const automationMigration = await readFile(new URL("../supabase/migrations/015_phase4a_automation_foundation.sql", import.meta.url), "utf8");
const automationTimingMigration = await readFile(new URL("../supabase/migrations/016_phase4a_automation_timing_rules.sql", import.meta.url), "utf8");
const checkinRpcFixMigration = await readFile(new URL("../supabase/migrations/017_fix_checkin_rpc_overload.sql", import.meta.url), "utf8");
const checkoutRpcFixMigration = await readFile(new URL("../supabase/migrations/018_fix_checkout_rpc_overload.sql", import.meta.url), "utf8");
const adminCleanupMigration = await readFile(new URL("../supabase/migrations/019_manager_admin_month_cleanup.sql", import.meta.url), "utf8");
const fullDeleteMigration = await readFile(new URL("../supabase/migrations/020_full_delete_test_booking.sql", import.meta.url), "utf8");
const publicBookingRequestMigration = await readFile(new URL("../supabase/migrations/021_public_booking_request_form.sql", import.meta.url), "utf8");
const migrationDir = new URL("../supabase/migrations/", import.meta.url);
const migrationFiles = (await readdir(migrationDir)).filter((name) => name.endsWith(".sql")).sort();
const allMigrations = (await Promise.all(migrationFiles.map(async (name) => [
  name,
  await readFile(new URL(name, migrationDir), "utf8")
]))).map(([name, sql]) => `-- ${name}\n${sql}`).join("\n\n");

assert.ok(app.includes('from "./supabase.js"'), "app must use the Supabase client");
assert.ok(!app.includes("trz-pms-phase1-state"), "business records must not be stored in localStorage");
assert.ok(!app.includes("createInitialState"), "browser app must not seed local business records");
assert.ok(app.includes("verify_pms_access_code"), "app must unlock through the PMS access code RPC");
assert.ok(app.includes("change_manager_security_code"), "app must change manager code through RPC");
assert.ok(app.includes('localStorage.setItem(accessSessionKey, "true")'), "PMS access unlock must persist in localStorage");
assert.ok(app.includes('localStorage.getItem(accessSessionKey) === "true"'), "PMS access must restore from localStorage on reload");
assert.ok(app.includes("localStorage.removeItem(accessSessionKey)"), "PMS Lock button must clear persisted access");
assert.ok(!app.includes("sessionStorage.setItem(accessSessionKey"), "PMS access must not be session-only");
assert.ok(app.includes("trz-manager-view-unlocked"), "Manager View must use browser session-only visibility state");
assert.ok(app.includes("unlock-manager-view"), "Manager View must have a discreet unlock control");
assert.ok(app.includes("Normal View is active"), "Normal View must be the default finance visibility mode");
assert.ok(app.includes("Manager View is active"), "Manager View must reveal sensitive finance visibility");
assert.ok(app.includes("Operational Cash on Hand"), "Normal View must show operational cash on hand");
assert.ok(app.includes("Cash available for approved operating expenses."), "operational cash card must explain allowed use");
assert.ok(app.includes('wallet.name.toLowerCase() === "cash"'), "operational cash card must use only the Cash wallet");
assert.ok(app.includes("Low cash available"), "operational cash card should support a low-cash warning");
assert.ok(app.includes("dashboard-page"), "dashboard must use the premium dashboard layout wrapper");
assert.ok(app.includes("dashboardUpcomingArrivals"), "dashboard must show upcoming arrivals from existing booking data");
assert.ok(app.includes("dashboardRecentActivity"), "dashboard must show recent activity from existing loaded data");
assert.ok(app.includes("navIcon"), "navigation must support sidebar-style icon labels without changing tab logic");
assert.ok(app.includes("AUTO_REFRESH_MS = 10000"), "PMS must poll Supabase so public booking requests appear without manual refresh");
assert.ok(app.includes("refreshDataIfIdle"), "PMS auto-refresh must update existing calendar/bookings data");
assert.ok(app.includes("appStateFingerprint"), "PMS auto-refresh must compare old and new data before rendering");
assert.ok(app.includes("stateFingerprint === nextFingerprint"), "PMS auto-refresh must skip rendering when data has not changed");
assert.ok(app.includes("window.scrollTo(scrollX, scrollY)"), "PMS auto-refresh must preserve scroll position when data changes");
assert.ok(app.includes("shouldSkipAutoRefresh"), "PMS auto-refresh must avoid wiping active forms or modals");
assert.ok(styles.includes(".dashboard-kpi"), "dashboard must include premium KPI card styling");
assert.ok(styles.includes(".dashboard-content-grid"), "dashboard must include upgraded dashboard content hierarchy");
assert.ok(styles.includes(".dashboard-list-row"), "dashboard arrivals/activity rows must be styled");
assert.ok(styles.includes("position: fixed"), "desktop sidebar navigation styling must be present");
assert.ok(supabase.includes("VITE_SUPABASE_URL"), "Supabase URL must come from VITE_SUPABASE_URL");
assert.ok(supabase.includes("VITE_SUPABASE_ANON_KEY"), "Supabase anon key must come from VITE_SUPABASE_ANON_KEY");
assert.ok(!supabase.includes("/auth/v1/token"), "Supabase Auth login must not be used in the access-code phase");
assert.ok(indexHtml.includes('rel="manifest"'), "PWA manifest must be linked from index.html");
assert.ok(indexHtml.includes('name="theme-color"'), "PWA theme color meta tag must exist");
assert.ok(indexHtml.includes("mobile-web-app-capable"), "PWA mobile web app meta tag must exist");
assert.ok(!indexHtml.includes("apple-mobile-web-app-capable"), "Deprecated Apple capable meta tag must be removed");
assert.equal(manifestData.short_name, "TRZ PMS", "PWA manifest must use TRZ PMS short name");
assert.equal(manifestData.display, "standalone", "PWA manifest must request standalone display");
assert.ok(manifestData.icons.some((icon) => icon.src === "/icons/icon-192.png" && icon.sizes === "192x192" && icon.type === "image/png"), "PWA manifest must include 192 PNG icon");
assert.ok(manifestData.icons.some((icon) => icon.src === "/icons/icon-512.png" && icon.sizes === "512x512" && icon.type === "image/png"), "PWA manifest must include 512 PNG icon");
assert.ok(manifestData.icons.some((icon) => icon.src === "/icons/icon-maskable-512.png" && icon.purpose === "maskable" && icon.type === "image/png"), "PWA manifest must include maskable PNG icon");
assert.ok(app.includes('navigator.serviceWorker.register("./sw.js")'), "app must register the service worker");
assert.ok(app.includes("shortCalendarStatus"), "mobile calendar labels must be shortened without changing status logic");
assert.ok(app.includes("shortBookingCode"), "mobile calendar labels must use compact booking codes");
assert.ok(styles.includes("@media (max-width: 760px)"), "mobile layout rules must exist");
assert.ok(styles.includes("min-height: 44px"), "mobile tap targets must be at least 44px");
assert.ok(styles.includes("overflow-x: auto"), "mobile tables and panels must support horizontal scrolling");
assert.ok(styles.includes("max-height: calc(100dvh - 16px)"), "mobile modals must fit within the viewport");
assert.ok(styles.includes("position: sticky"), "mobile modal action footers must stay reachable");
assert.ok(styles.includes("min-width: 640px"), "mobile tables must preserve readable columns with horizontal scroll");
assert.ok(server.includes('".webmanifest": "application/manifest+json"'), "server must serve webmanifest MIME type");
assert.ok(server.includes('".svg": "image/svg+xml"'), "server must serve SVG icon MIME type");
assert.ok(serviceWorker.includes("CACHE_ASSETS"), "service worker must define an app shell cache");
assert.ok(serviceWorker.includes("./index.html"), "service worker must cache HTML shell");
assert.ok(serviceWorker.includes("./styles.css"), "service worker must cache CSS shell");
assert.ok(serviceWorker.includes("./src/app.js"), "service worker must cache JS shell");
assert.ok(serviceWorker.includes("./icons/icon-192.png"), "service worker must cache 192 PNG icon shell asset");
assert.ok(serviceWorker.includes("./icons/icon-512.png"), "service worker must cache 512 PNG icon shell asset");
assert.ok(serviceWorker.includes("./icons/icon-maskable-512.png"), "service worker must cache maskable PNG icon shell asset");
assert.ok(!serviceWorker.includes("./env.js"), "service worker must not cache env.js");
assert.ok(serviceWorker.includes('url.pathname === "/env.js"'), "service worker must bypass env.js");
assert.ok(serviceWorker.includes('url.pathname.startsWith("/api/")'), "service worker must bypass API endpoints");
assert.ok(serviceWorker.includes("url.origin !== self.location.origin"), "service worker must bypass cross-origin live data");
assert.ok(serviceWorker.includes("supabase.co"), "service worker must explicitly avoid Supabase requests");
assert.ok(serviceWorker.includes("OFFLINE_HTML"), "service worker must provide a simple offline page");
assert.ok(serviceWorker.includes("Read-only notice"), "offline page must show read-only notice");
assert.ok(serviceWorker.includes("booking creation, payments, deposits, finance actions"), "offline page must block business operations in copy");
assert.ok(server.includes("/api/automation/send"), "server must expose automation send endpoint");
assert.ok(server.includes("sendAutomationEmail"), "server must call Resend email helper");
assert.ok(server.includes("[automation/send]"), "automation send endpoint must log readable failures");
assert.ok(server.includes("sendJson(res, 500"), "local email API errors must return JSON");
assert.ok(automationApi.includes("sendJson(res, 200") && automationApi.includes("sendJson(res, 500"), "Vercel automation API must always return JSON");
assert.ok(memoryApi.includes("sendJson(res, 200") && memoryApi.includes("sendJson(res, 500"), "Vercel memory API must always return JSON");
assert.ok(automationApi.includes("process.env") && memoryApi.includes("process.env"), "Vercel email APIs must use server-side environment variables");
assert.ok(vercelConfig.includes("((?!api/).*"), "Vercel SPA rewrite must not swallow /api routes");
assert.ok(!server.includes("RESEND_API_KEY:"), "server must not expose RESEND_API_KEY through env.js");
assert.ok(resendHelper.includes("RESEND_API_KEY"), "Resend helper must use RESEND_API_KEY");
assert.ok(resendHelper.includes("The Resthouse Zamboanga <bookings@theresthousezamboanga.com>"), "Resend sender must use TRZ display name and verified domain");
assert.ok(resendHelper.includes("theresthousezamboanga@gmail.com"), "Reply-To must be TRZ Gmail");
assert.ok(resendHelper.includes("https://api.resend.com/emails"), "Resend helper must call Resend email API");
assert.ok(resendHelper.includes('setQueueStatus(config, queue.id, "sent"'), "Resend helper must mark sent on success");
assert.ok(resendHelper.includes('setQueueStatus(config, queue.id, "failed"'), "Resend helper must mark failed on error");
assert.ok(resendHelper.includes("readableError"), "Resend helper must preserve readable provider/setup errors");
assert.ok(resendHelper.includes('queue.automation_type !== "booking_confirmation"'), "Email sending must reject non-confirmation automation types");
assert.ok(!resendHelper.includes("Penalties and Damages.pdf"), "Booking confirmation must not attach PDF documents (inline-only redesign)");
assert.ok(!resendHelper.includes("TRZ HOUSE RULES.pdf"), "Booking confirmation must not attach PDF documents (inline-only redesign)");
assert.ok(!resendHelper.includes("TRZ LOCATION.pdf"), "Booking confirmation must not attach PDF documents (inline-only redesign)");
assert.ok(resendHelper.includes("Booking Confirmed"), "Booking confirmation must include branded confirmed badge text");
assert.ok(resendHelper.includes("Payment Summary"), "Booking confirmation must include payment summary");
assert.ok(resendHelper.includes("Your Private Paradise. Your Home Away From Home."), "Booking confirmation must include TRZ hero tagline");
assert.ok(resendHelper.includes("Explore The Resthouse"), "Booking confirmation must include resort photo section");
assert.ok(resendHelper.includes("Your Package"), "Booking confirmation must include dynamic package section");
assert.ok(resendHelper.includes("Your Stay Guide"), "Booking confirmation must include stay guide reminders");
assert.ok(resendHelper.includes("Caring for Your Home Away"), "Booking confirmation must include care guidelines");
assert.ok(resendHelper.includes("Registered Guests Only"), "Booking confirmation must include actual TRZ house rules");
assert.ok(resendHelper.includes("No Pets Allowed"), "Booking confirmation must include no-pets rule");
assert.ok(resendHelper.includes("Drinks & Corkage"), "Booking confirmation must include drinks corkage rule");
assert.ok(!resendHelper.includes("food corkage"), "Booking confirmation must not include removed food corkage language");
assert.ok(!resendHelper.includes("kitchen access"), "Booking confirmation must not include removed kitchen access language");
assert.ok(!resendHelper.includes("catering"), "Booking confirmation must not include removed catering language");
assert.ok(resendHelper.includes('content: bytes.toString("base64")'), "Booking confirmation attachments must use Base64 file content");
assert.ok(resendHelper.includes("emailPayload.attachments"), "Attachments must be applied only when present");
assert.ok(resendHelper.includes("inlineImageFiles"), "Booking confirmation must include inline resort photo assets");
assert.ok(resendHelper.includes("content_id"), "Inline email photos must use CID attachments");
assert.ok(resendHelper.includes("cid:trz-hero"), "Booking confirmation must embed hero photo inline");
assert.ok(resendHelper.includes("cid:trz-pool"), "Booking confirmation must embed pool photo inline");
assert.ok(resendHelper.includes("cid:trz-location"), "Booking confirmation must embed location map inline");
assert.ok(resendHelper.includes("packageInclusions"), "Booking confirmation must derive inclusions from package data");
assert.ok(!resendHelper.includes("buildCheckinReminderEmail"), "Check-in reminder email builder must be removed");
assert.ok(!resendHelper.includes("buildThankYouEmail"), "Thank-you email builder must be removed");
assert.ok(!resendHelper.includes("CHECK-IN REMINDER"), "Check-in reminder branded template must be removed");
assert.ok(!resendHelper.includes("THANK YOU FOR STAYING"), "Thank-you branded template must be removed");
assert.ok(!resendHelper.includes("Check-in Reminder"), "Check-in reminder subject text must be removed");
assert.ok(!resendHelper.includes("Thank You"), "Thank-you subject text must be removed");
assert.ok(!resendHelper.includes("Full payment/balance must be settled before access"), "Check-in reminder payment/balance text must be removed");
assert.ok(bookingRequestHtml.includes("Booking Request Form"), "public booking request form must exist");
assert.ok(bookingRequestHtml.includes("./src/booking-request.js"), "public booking request form must load its script");
assert.ok(bookingRequestHtml.includes("Our team will review your request"), "public form must tell guests staff will review the request");
assert.ok(bookingRequestHtml.includes("online payment") === false, "public form must not mention online payment");
assert.ok(bookingRequestCss.includes("@media (max-width: 560px)"), "public form must include mobile-first layout rules");
assert.ok(bookingRequestCss.includes("min-height: 48px"), "public form controls must have large mobile touch targets");
assert.ok(bookingRequestJs.includes("showPicker"), "public booking form date inputs must open the date picker from the input body");
assert.ok(bookingRequestJs.includes('select("packages"'), "public form must load current PMS packages");
assert.ok(bookingRequestJs.includes('select("package_versions"'), "public form must load current package versions");
assert.ok(bookingRequestJs.includes("submit_public_booking_request"), "public form must submit through the public request RPC");
assert.ok(!bookingRequestJs.includes("queue_booking_automation"), "public request form must not queue email automation");
assert.ok(!bookingRequestJs.includes("automation_queue"), "public request form must not touch automation queue directly");
assert.ok(!bookingRequestJs.includes("calculateBasePrice"), "public request form must not show price estimator logic");
assert.ok(publicBookingRequestMigration.includes("create or replace function public.submit_public_booking_request"), "public request RPC must exist");
assert.ok(publicBookingRequestMigration.includes("'Deposit Requested'"), "public request RPC must create Deposit Requested bookings");
assert.ok(publicBookingRequestMigration.includes("delete from public.automation_queue"), "public request RPC must remove auto-created request email queue records");
assert.ok(publicBookingRequestMigration.includes("Public booking request submitted"), "public request RPC must audit submissions");
assert.ok(!publicBookingRequestMigration.includes("add value") || !publicBookingRequestMigration.includes("'Pending'"), "public request migration must not add a Pending status");
assert.ok(!resendHelper.includes("comfortable and enjoyable stay"), "Thank-you message text must be removed");
assert.ok(!resendHelper.includes("Book Again"), "Thank-you repeat booking section must be removed");
assert.ok(foundationMigration.includes("bookings_no_active_overlap"), "migration must enforce calendar conflict prevention");
assert.ok(foundationMigration.includes("recompute_booking_financials"), "migration must keep booking snapshots ledger-derived");
assert.ok(foundationMigration.includes("'Security Deposit Liability'"), "migration must separate deposit liability from revenue");
assert.ok(accessMigration.includes("create table if not exists settings"), "access migration must create protected settings table");
assert.ok(accessMigration.includes("revoke all on table settings from anon"), "settings must not be directly readable by anon");
assert.ok(accessMigration.includes("security definer"), "code verification must happen through security-definer RPCs");
assert.ok(accessMigration.includes("to anon"), "Phase 1 anon RLS policies must be explicit");
assert.ok(app.includes("Security deposit received?"), "booking creation must include optional deposit shortcut");
assert.ok(app.includes("Checkout Settlement"), "checkout status must trigger settlement UI");
assert.ok(app.includes("Check-In Payment"), "check-in status must trigger payment UI");
assert.ok(app.includes("perform_checkin_payment"), "check-in payment must use RPC");
assert.ok(app.includes("start_meter_reading"), "check-in RPC payload must include canonical optional start meter parameter");
assert.ok(app.includes('form.dataset.submitting === "true"'), "forms must guard against quick duplicate submits");
assert.ok(app.includes("perform_checkout_settlement"), "checkout settlement must use RPC");
assert.ok(app.includes("end_meter_reading"), "checkout RPC payload must include canonical optional end meter parameter");
assert.ok(app.includes("electricity_rate_per_kwh"), "checkout RPC payload must include canonical optional electricity rate parameter");
assert.ok(!app.includes("sendThankYouAfterCheckout"), "checkout completion must not send thank-you email");
assert.ok(!app.includes('queueBookingAutomation(bookingId, "thank_you")'), "thank-you queue must not be triggered after checkout completion");
assert.ok(app.includes("Monthly Starting Reading"), "Operations must support monthly electricity baseline");
assert.ok(app.includes("Current Reading"), "Operations must support current electricity readings");
assert.ok(app.includes("Usage / Estimate"), "Operations must show electricity usage estimate");
assert.ok(app.includes("Reading Log"), "Operations must show electricity reading log");
assert.ok(!app.includes("correct_booking_electricity"), "simplified electricity UI must not use booking correction RPC");
assert.ok(!app.includes("function statusForm"), "old status-change form must stay removed");
assert.ok(!app.includes("updateBookingStatus"), "old status-change workflow must stay removed");
assert.ok(!app.includes('action === "complete"'), "old Complete Booking handler must stay removed");
assert.ok(!app.includes("Manager Record Transaction"), "manual transaction UI must stay hidden from Finance");
assert.ok(app.includes('verify_manager_security_code", { input_code: fields.manager_code }'), "manual transaction writes must verify manager code first");
assert.ok(app.includes('verify_manager_security_code", { input_code: managerCode }'), "Manager View unlock must verify manager code first");
assert.ok(app.includes("Manager View is required for transaction reversals"), "transaction reversals must require Manager View");
assert.ok(app.includes("Owner Harvest"), "Manager View Finance must include Owner Harvest");
assert.ok(app.includes('data-action="owner-harvest"'), "Owner Harvest form must exist");
assert.ok(app.includes('verify_manager_security_code", { input_code: fields.manager_code }'), "Owner Harvest must require Manager Security Code");
assert.ok(app.includes("Automation Queue"), "Settings must show Automation Queue");
assert.ok(app.includes("Admin Tools"), "Settings must include Manager-only Admin Tools");
assert.ok(app.includes('isManagerViewUnlocked() ? adminToolsView() : ""'), "Admin Tools must render only in Manager View");
assert.ok(app.includes('data-action="admin-cleanup-preview"'), "Admin Tools must require a preview before delete");
assert.ok(app.includes('data-action="admin-cleanup-delete"'), "Admin Tools must include a final delete action");
assert.ok(app.includes("admin_delete_data_by_month"), "Admin Tools must call the cleanup RPC");
assert.ok(app.includes("Confirmation text must exactly match"), "Admin delete must enforce exact confirmation text in UI");
assert.ok(app.includes("Emails send through the local server"), "Automation must explain server email sending");
assert.ok(app.includes("set_automation_queue_status"), "Automation status changes must use RPC");
assert.ok(app.includes("Email / Automation"), "Booking modal must show email automation controls");
assert.ok(!app.includes("Create/Queue Confirmation Email"), "Booking modal must not show separate queue confirmation action");
assert.ok(!app.includes("Mark Confirmation as Sent"), "Booking modal must not show manual sent action");
assert.ok(!app.includes("Skip Confirmation"), "Booking modal must not show skip confirmation action");
assert.ok(app.includes("Retry Failed Email"), "Booking modal must retry failed email");
assert.ok(app.includes("Confirmation email queued"), "Booking creation must show queued confirmation notice");
assert.ok(app.includes("No guest email; confirmation skipped"), "Booking creation must show missing email skip notice");
assert.ok(app.includes("queue_booking_automation"), "Booking modal must use queue automation RPC");
assert.ok(app.includes("Ready to send"), "Due pending automation items must show ready to send");
assert.ok(app.includes('fetch("/api/automation/send"'), "Automation queue must call local send endpoint");
assert.ok(app.includes("markAutomationFailed"), "Automation send failures must update queue status to failed");
assert.ok(app.includes("readEmailApiResponse"), "Frontend email sends must use safe response parsing");
assert.ok(app.includes("Email server unreachable"), "Automation send failures must show local server connection errors");
assert.ok(app.includes("Email server returned an unreadable response"), "Automation send failures must show non-JSON endpoint errors");
assert.ok(app.includes("Email server returned an empty response"), "Automation send failures must show empty endpoint responses");
assert.ok(!app.includes("await res.json()"), "Frontend email sends must not crash on empty or non-JSON API responses");
assert.ok(app.includes("Send Email"), "Automation queue must expose real send action");
assert.ok(app.includes("Send Confirmation Email"), "Booking modal must expose real confirmation send action");
assert.ok(!app.includes("Send Check-in Reminder"), "Booking modal must not expose check-in reminder send action");
assert.ok(app.includes("sendBookingAutomationNow"), "Booking modal send buttons must queue if needed and send immediately");
assert.ok(app.includes("Mark as Sent"), "Automation queue must support manual sent status");
assert.ok(app.includes("Mark as Failed"), "Automation queue must support manual failed status");
assert.ok(app.includes("Skip"), "Automation queue must support skip action");
assert.ok(app.includes("Retry"), "Automation queue must support retry action");
assert.ok(app.includes("guestProfileModal"), "guest profile/history modal must exist");
assert.ok(app.includes("Booking Timeline"), "booking action modal must show timeline");
assert.ok(app.includes("data-booking-search-form"), "booking search must exist");
assert.ok(app.includes("booking-notes"), "booking notes update form must exist");
assert.ok(app.includes("timelineEventsForBooking"), "booking timeline must be derived from existing records");
assert.ok(app.includes("Edit Booking"), "booking action modal must support edit/reschedule");
assert.ok(app.includes("Confirm Booking"), "Deposit Requested bookings must support staff confirmation");
assert.ok(app.includes("confirmBookingDepositModal"), "Confirm Booking must open a deposit/payment modal first");
assert.ok(app.includes("Save Deposit and Confirm Booking"), "staff confirmation must require the deposit modal workflow");
assert.ok(app.includes("Security Deposit Liability"), "confirmation deposit must remain a liability");
assert.ok(app.includes("Booking confirmed after payment verification"), "staff confirmation must create an audit reason");
assert.ok(app.includes("Confirm booking first before sending confirmation email."), "confirmation email must be blocked until booking is Confirmed");
assert.ok(app.includes("booking?.status !== \"Confirmed\""), "email send function must enforce Confirmed status");
assert.ok(app.includes("bindDatePickerOpeners"), "PMS date inputs must open the date picker from the input body");
assert.ok(app.includes("bindModalBackdropClose"), "PMS modals must close by clicking the overlay");
assert.ok(app.includes("event.target !== backdrop"), "modal overlay close must not trigger from inside modal content");
assert.ok(app.includes("Cancel Booking"), "booking action modal must support cancellation with reason");
assert.ok(app.includes("Archive Booking"), "completed/cancelled/refunded bookings must support archive");
assert.ok(app.includes("Manager View is required for testing deletes"), "Delete Booking must be Manager View only");
assert.ok(app.includes("confirmation_text"), "Delete Booking must send exact confirmation text to RPC");
assert.ok(app.includes("DELETE ${booking.booking_code}"), "Delete Booking must require DELETE booking-code confirmation");
assert.ok(app.includes("data-calendar-nav=\"prev\""), "calendar must support previous month navigation");
assert.ok(app.includes("data-calendar-nav=\"next\""), "calendar must support next month navigation");
assert.ok(app.includes("data-calendar-nav=\"today\""), "calendar must support today navigation");
assert.ok(app.includes("Record Expense"), "finance must support expense entry");
assert.ok(app.includes("data-action=\"transfer\""), "finance must support wallet transfers");
assert.ok(app.includes("Void/Reversal"), "transactions must support reversal action");
assert.ok(app.includes("reference_number"), "transactions must support reference numbers");
assert.ok(!app.includes("Wallet Movement"), "Finance must not show duplicate Wallet Movement section");
assert.ok(!app.includes("Today Revenue"), "Finance summary must not show Today Revenue");
assert.ok(!app.includes("Today Expenses"), "Finance summary must not show Today Expenses");
assert.ok(!app.includes("Today Net"), "Finance summary must not show Today Net");
assert.ok(app.includes("This Month Revenue"), "Finance summary must keep monthly revenue");
assert.ok(app.includes("Current Security Deposit Liability"), "Finance summary must keep deposit liability");
assert.ok(app.includes("slice(0, 10)"), "Transactions must show latest 10 rows only");
assert.ok(app.includes("type-badge"), "Transactions must show simple account type badges");
assert.ok(app.includes("Operations"), "Operations tab must exist for Phase 3A");
assert.ok(app.includes("Record Drink Sale"), "Operations must support drink sales");
assert.ok(app.includes("Stock Movement"), "Operations must support drink inventory movements");
assert.ok(app.includes("drinkCurrentStock"), "drink sales must use stock calculations");
assert.ok(financialWorkflowMigration.includes("perform_checkout_settlement"), "checkout settlement RPC must exist");
assert.ok(financialWorkflowMigration.includes("Checkout settlement is required"), "direct Checked Out status update must be guarded");
assert.ok(checkinWorkflowMigration.includes("perform_checkin_payment"), "check-in payment RPC must exist");
assert.ok(checkinWorkflowMigration.includes("Check-in payment confirmation is required"), "direct Checked In status update must be guarded");
assert.ok(deleteMigration.includes("delete_test_booking"), "testing delete RPC must exist");
assert.ok(styles.includes(".pill-deposit-requested { background: rgba(251,191,36"), "Deposit Requested status badge must be yellow");
assert.ok(styles.includes(".day-segment.deposit-requested"), "Deposit Requested calendar segment must have a specific yellow indicator");
assert.ok(styles.includes(".booking-card.s-deposit-requested{ border-left-color: #fbbf24"), "Deposit Requested booking cards must use yellow status color");
assert.ok(checkoutCompletesMigration.includes("set status = 'Completed'"), "checkout settlement must complete bookings");
assert.ok(hardeningMigration.includes("'checkin_payment'"), "check-in audit must be written by RPC");
assert.ok(hardeningMigration.includes("'checkout_settlement'"), "checkout settlement audit must be written by RPC");
assert.ok(hardeningMigration.includes("'delete_blocked'"), "blocked delete attempts must be audited");
assert.ok(hardeningMigration.includes("Check-in payment confirmation is required"), "hardening migration must keep check-in status guard");
assert.ok(bookingManagementMigration.includes("Only Completed, Cancelled, or Refunded bookings can be archived"), "archive status guard must be enforced in SQL");
assert.ok(financeControlsMigration.includes("add value if not exists 'Expense'"), "Expense account type must be added");
assert.ok(financeControlsMigration.includes("create table if not exists public.expenses"), "expenses table must exist");
assert.ok(financeControlsMigration.includes("create table if not exists public.daily_closings"), "daily closings table must exist");
assert.ok(financeControlsMigration.includes("alter column booking_id drop not null"), "ledger entries must allow unlinked finance records");
assert.ok(drinksMigration.includes("create table if not exists public.drink_products"), "drink products table must exist");
assert.ok(drinksMigration.includes("create table if not exists public.drink_inventory_movements"), "drink movements table must exist");
assert.ok(drinksMigration.includes("create table if not exists public.drink_sales"), "drink sales table must exist");
assert.ok(drinksMigration.includes("Red Horse 500ml"), "default drink products must be seeded");
assert.ok(electricityMigration.includes("add column if not exists start_meter"), "bookings must store start meter");
assert.ok(electricityMigration.includes("generated always as"), "electricity usage/cost must be generated from readings");
assert.ok(electricityMigration.includes("correct_booking_electricity"), "manager correction RPC must exist");
assert.ok(simplifiedElectricityMigration.includes("create table if not exists public.electricity_monthly_baselines"), "electricity baseline table must exist");
assert.ok(simplifiedElectricityMigration.includes("create table if not exists public.electricity_readings"), "electricity readings table must exist");
assert.ok(simplifiedElectricityMigration.includes("rate_per_kwh > 0"), "electricity rate must be positive");
assert.ok(ownerHarvestMigration.includes("add value if not exists 'Owner Harvest'"), "Owner Harvest account type must be added");
assert.ok(ownerHarvestMigration.includes("create table if not exists public.owner_harvests"), "owner harvest table must exist");
assert.ok(ownerHarvestMigration.includes("amount > 0"), "owner harvest amount must be positive");
assert.ok(automationMigration.includes("create table if not exists public.automation_queue"), "automation queue table must exist");
assert.ok(automationMigration.includes("unique (booking_id, automation_type)"), "automation queue must prevent duplicate booking/type records");
assert.ok(automationMigration.includes("booking_confirmation"), "booking confirmation automation type must exist");
assert.ok(automationMigration.includes("checkin_reminder"), "check-in reminder automation type must exist");
assert.ok(automationMigration.includes("thank_you"), "thank-you automation type must exist");
assert.ok(automationMigration.includes("Guest email missing."), "missing email must be handled clearly");
assert.ok(automationMigration.includes("new.status = 'Completed'"), "thank-you automation must queue after completion");
assert.ok(automationMigration.includes("target_booking.status in ('Cancelled', 'Refunded', 'Archived')"), "cancelled/refunded/archived reminders must be skipped");
assert.ok(automationMigration.includes("set_automation_queue_status"), "automation queue status RPC must exist");
assert.ok(automationMigration.includes("grant execute on function public.set_automation_queue_status"), "automation queue status RPC must be callable");
assert.ok(automationTimingMigration.includes("queue_scheduled_for := now();"), "booking confirmation must queue immediately");
assert.ok(automationTimingMigration.includes("queue_scheduled_for := target_booking.start_at - interval '3 days'"), "check-in reminder must queue 3 days before check-in");
assert.ok(automationTimingMigration.includes("target_booking.status <> 'Completed'"), "thank-you must only queue after completed status");
assert.ok(automationTimingMigration.includes("Guest email missing."), "missing email must remain skipped with reason");
assert.ok(checkinRpcFixMigration.includes("drop function if exists public.perform_checkin_payment(uuid, numeric, uuid, numeric, uuid, text);"), "old 6-argument check-in RPC overload must be dropped");
assert.ok(checkinRpcFixMigration.includes("drop function if exists public.perform_checkin_payment(uuid, numeric, uuid, numeric, uuid, text, numeric);"), "old 7-argument check-in RPC overload must be dropped before recreation");
assert.equal((checkinRpcFixMigration.match(/create or replace function public\.perform_checkin_payment/g) || []).length, 1, "check-in RPC fix migration must recreate exactly one canonical function");
assert.ok(checkinRpcFixMigration.includes("start_meter_reading numeric default null"), "canonical check-in RPC must keep optional start meter parameter");
assert.ok(checkinRpcFixMigration.includes("if target_booking.status = 'Checked In'"), "canonical check-in RPC must block duplicate check-in submissions");
assert.ok(checkoutRpcFixMigration.includes("p.proname = 'perform_checkout_settlement'"), "checkout RPC fix migration must drop all checkout overloads dynamically");
assert.equal((checkoutRpcFixMigration.match(/create or replace function public\.perform_checkout_settlement/g) || []).length, 1, "checkout RPC fix migration must recreate exactly one canonical function");
assert.ok(checkoutRpcFixMigration.includes("end_meter_reading numeric default null"), "canonical checkout RPC must keep optional end meter parameter");
assert.ok(checkoutRpcFixMigration.includes("electricity_rate_per_kwh numeric default null"), "canonical checkout RPC must keep optional electricity rate parameter");
assert.ok(checkoutRpcFixMigration.includes("if target_booking.status = 'Completed'"), "canonical checkout RPC must block duplicate checkout submissions");
assert.ok(!checkoutRpcFixMigration.includes("create or replace function public.record_owner_harvest"), "owner harvest RPC overload must not be introduced");
assert.ok(!checkoutRpcFixMigration.includes("create or replace function public.record_expense"), "expense RPC overload must not be introduced");
assert.ok(!checkoutRpcFixMigration.includes("create or replace function public.record_transfer"), "transfer RPC overload must not be introduced");
assert.ok(adminCleanupMigration.includes("create or replace function public.admin_delete_data_by_month"), "manager month cleanup RPC must exist");
assert.ok(adminCleanupMigration.includes("security definer"), "manager month cleanup must run as a controlled security-definer RPC");
assert.ok(adminCleanupMigration.includes("public.verify_manager_security_code(manager_code)"), "manager month cleanup must verify Manager Security Code");
assert.ok(adminCleanupMigration.includes("dry_run boolean default true"), "manager month cleanup must support preview/dry-run mode");
assert.ok(adminCleanupMigration.includes("expected_confirmation := 'DELETE ' || upper(month_label)"), "manager month cleanup must require DELETE MONTH YEAR confirmation text");
assert.ok(adminCleanupMigration.includes("where b.start_at >= period_start"), "manager month cleanup must target bookings by check-in month");
assert.ok(adminCleanupMigration.includes("delete from public.automation_queue"), "manager month cleanup must delete booking automation records");
assert.ok(adminCleanupMigration.includes("delete from public.security_deposits"), "manager month cleanup must delete booking deposit helpers");
assert.ok(adminCleanupMigration.includes("delete from public.ledger_lines"), "manager month cleanup must delete ledger lines before ledger entries");
assert.ok(adminCleanupMigration.includes("delete from public.ledger_entries"), "manager month cleanup must delete linked ledger entries");
assert.ok(adminCleanupMigration.includes("delete from public.expenses"), "manager month cleanup must delete booking-linked expenses");
assert.ok(adminCleanupMigration.includes("delete from public.drink_sales"), "manager month cleanup must delete booking-linked drink sales");
assert.ok(adminCleanupMigration.includes("delete from public.bookings"), "manager month cleanup must delete selected-month bookings");
assert.ok(adminCleanupMigration.includes("delete from public.guests"), "manager month cleanup must delete only guests without remaining bookings");
assert.ok(!adminCleanupMigration.includes("delete from public.packages"), "manager month cleanup must not delete packages");
assert.ok(!adminCleanupMigration.includes("delete from public.package_versions"), "manager month cleanup must not delete package versions");
assert.ok(!adminCleanupMigration.includes("delete from public.wallets"), "manager month cleanup must not delete wallets");
assert.ok(!adminCleanupMigration.includes("delete from public.settings"), "manager month cleanup must not delete settings");
assert.ok(!adminCleanupMigration.includes("delete from public.booking_counters"), "manager month cleanup must not delete booking counters");
assert.ok(adminCleanupMigration.includes("grant execute on function public.admin_delete_data_by_month"), "manager month cleanup RPC must be callable by the frontend");
assert.ok(fullDeleteMigration.includes("proname = 'delete_test_booking'"), "full delete migration must drop old delete_test_booking overloads");
assert.ok(fullDeleteMigration.includes("confirmation_text text"), "full delete RPC must require confirmation text");
assert.ok(fullDeleteMigration.includes("expected_confirmation := 'DELETE ' || target_booking.booking_code"), "full delete RPC must require DELETE booking-code text");
assert.ok(fullDeleteMigration.includes("public.verify_manager_security_code(manager_code)"), "full delete RPC must verify Manager Security Code");
assert.ok(fullDeleteMigration.includes("delete from public.automation_queue"), "full delete RPC must delete booking automation records");
assert.ok(fullDeleteMigration.includes("delete from public.security_deposits"), "full delete RPC must delete booking deposit helper");
assert.ok(fullDeleteMigration.includes("delete from public.ledger_lines"), "full delete RPC must delete ledger lines before ledger entries");
assert.ok(fullDeleteMigration.includes("delete from public.ledger_entries"), "full delete RPC must delete booking ledger entries");
assert.ok(fullDeleteMigration.includes("delete from public.expenses"), "full delete RPC must delete booking-linked expenses");
assert.ok(fullDeleteMigration.includes("delete from public.drink_sales"), "full delete RPC must delete booking-linked drink sales");
assert.ok(fullDeleteMigration.includes("delete from public.drink_inventory_movements"), "full delete RPC must delete booking-linked drink movements");
assert.ok(!fullDeleteMigration.includes("delete from public.audit_logs"), "full delete RPC must leave append-only audit logs intact");
assert.ok(fullDeleteMigration.includes("delete from public.bookings"), "full delete RPC must delete only the selected booking");
assert.ok(fullDeleteMigration.includes("delete from public.guests"), "full delete RPC must delete guest only if no bookings remain");
assert.ok(!fullDeleteMigration.includes("delete from public.packages"), "full delete RPC must not delete packages");
assert.ok(!fullDeleteMigration.includes("delete from public.package_versions"), "full delete RPC must not delete package versions");
assert.ok(!fullDeleteMigration.includes("delete from public.wallets"), "full delete RPC must not delete wallets");
assert.ok(!fullDeleteMigration.includes("delete from public.settings"), "full delete RPC must not delete settings");
assert.ok(!fullDeleteMigration.includes("delete from public.booking_counters"), "full delete RPC must not delete booking counters");
assertNoUnsafeRpcOverloads(allMigrations, {
  perform_checkin_payment: ["uuid", "numeric", "uuid", "numeric", "uuid", "text", "numeric"],
  perform_checkout_settlement: ["uuid", "numeric", "text", "numeric", "uuid", "numeric", "numeric"],
  verify_pms_access_code: ["text"],
  verify_manager_security_code: ["text"],
  change_pms_access_code: ["text", "text"],
  change_manager_security_code: ["text", "text"],
  set_automation_queue_status: ["uuid", "text", "text"],
  delete_test_booking: ["uuid", "text", "text"],
  admin_delete_data_by_month: ["integer", "integer", "text", "text", "boolean"],
  submit_public_booking_request: ["date", "date", "uuid", "integer", "text", "text", "text", "text", "text", "text", "boolean", "boolean", "boolean"]
});

console.log("Persistence boundary tests passed.");

function assertNoUnsafeRpcOverloads(sql, expectedSignatures) {
  for (const [name, expected] of Object.entries(expectedSignatures)) {
    const signatures = rpcSignatures(sql, name);
    assert.ok(signatures.length > 0, `${name} RPC must be defined in migrations`);
    const unique = new Set(signatures.map((signature) => signature.join(",")));
    const expectedKey = expected.join(",");
    if (unique.size > 1) {
      assert.ok(
        sql.includes(`p.proname = '${name}'`) || sql.includes(`drop function if exists public.${name}`),
        `${name} overloads must have an explicit cleanup migration`
      );
    }
    assert.equal(signatures.at(-1).join(","), expectedKey, `${name} latest signature must be canonical`);
  }
}

function rpcSignatures(sql, name) {
  const pattern = new RegExp(`create\\s+or\\s+replace\\s+function\\s+(?:public\\.)?${name}\\s*\\(([^)]*)\\)`, "gi");
  const signatures = [];
  for (const match of sql.matchAll(pattern)) {
    signatures.push(match[1]
      .split(",")
      .map((part) => part.trim())
      .filter(Boolean)
      .map((part) => part.replace(/\s+default\s+.+$/i, "").trim().split(/\s+/).at(-1).toLowerCase()));
  }
  return signatures;
}
